os:
  - osx
  - linux
language: node_js
node_js:
  - "6"
addons:
  apt:
    packages:
      - libsecret-1-dev
env:
  - GAUGE_TELEMETRY_ENABLED=false GAUGE_PREFIX=/tmp
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - curl -sSfL https://github.com/getgauge/gauge-tests/raw/master/install_latest_gauge_nightly.sh | bash
  - export PATH=$PATH:$GAUGE_PREFIX/bin
install:
  - gauge -v
  - gauge install js
script:
  - npm run build
  - npm test --silent